site_name: "Hospedagem de Aplicações na Rede IC"
theme: material
nav:
  - index.md
  - chave-ssh.md
  - ambiente-local.md
  - deploy.md
  - variaveis-de-ambiente.md
  - modo-build.md
  - comandos-permitidos.md
